--------------------------------------------------------
--  File created - Thursday-January-10-2013   
--------------------------------------------------------
REM INSERTING into PEDRO.CATEGORIA
SET DEFINE OFF;
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Todos',null);
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Outros',null);
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Auto','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Livros e Revistas','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Casa e Jardim','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Sa˙de','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Coleccion·veis e Arte','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Moda','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Desporto e Entretenimento','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Tecnologia e ElectrÛnica','Todos');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('PeçÁas Auto','Auto');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('VeÌculos','Auto');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Revistas','Livros e Revistas');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Manuais Escolares','Livros e Revistas');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Literatura','Livros e Revistas');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Literatura Infantil','Livros e Revistas');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Banda Desenhada','Livros e Revistas');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Animais','Casa e Jardim');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Jardinagem','Casa e Jardim');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('ImÛveis','Casa e Jardim');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('MobÌlia','Casa e Jardim');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Plantas e Flores','Casa e Jardim');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Higiene','Sa˙de');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('CosmÈticos','Sa˙de');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Selos','Coleccion·veis e Arte');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Moedas e Notas','Coleccion·veis e Arte');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Medalhas','Coleccion·veis e Arte');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Antiguidades','Coleccion·veis e Arte');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Arte','Coleccion·veis e Arte');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Vestu·rio','Moda');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('AcessÛrios','Moda');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Brinquedos','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Fitness e MusculaçÁ„o','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Filmes e Cinema','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('M˙sica','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('CaÁça e Pesca','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Campismo','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Futebol','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('NataçÁ„o','Desporto e Entretenimento');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('¡udio, TV e VÌdeo','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Consolas','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Fotografia','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Inform·tica','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('TelemÛveis e Telefones','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Gadgets','Tecnologia e ElectrÛnica');
Insert into PEDRO.CATEGORIA (NOME,PAI) values ('Circuitos','Tecnologia e ElectrÛnica');
