/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.ContaPessoal;

import Business_Layer.Anuncio;
import Business_Layer.AnuncioVenda;
import Business_Layer.ComparadorATerminar;
import Business_Layer.Leilao;
import Business_Layer.ModoVenda;
import Business_Layer.Transaccao;
import Presentation_Layer.Sale_Squared;
import Presentation_Layer.Tabelas.Tabela_Licitacao;
import java.util.Set;
import java.util.TreeSet;

/**
 *
 * @author ricardobranco
 */
public class Actividade extends javax.swing.JPanel {

    private final Sale_Squared root;

    /**
     * Creates new form Actividade
     */
    public Actividade(final Sale_Squared root) {
        this.root = root;
        initComponents();
        compras.add(new Tabela_Licitacao(root, getVendas()), "Compras");

        lic.add(new Tabela_Licitacao(root, getLeiloes()), "Leiloes");

    }

    private Set<Anuncio> getLeiloes() {
        Set<Anuncio> res = new TreeSet<>(new ComparadorATerminar());
        for (Transaccao t : this.root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getTransaccoes().values()) {
            AnuncioVenda a = (AnuncioVenda) t.getAnuncio();
            ModoVenda mv = a.getTipoVenda();
            if (mv.getClass().getSimpleName().equals("Leilao") && t.getComprador().getUsername().equals(Sale_Squared.UTILIZADOR)) {
                res.add(a);
            }

        }

        return res;
    }

    private Set<Anuncio> getVendas() {
        Set<Anuncio> res = new TreeSet<>(new ComparadorATerminar());
        for (Transaccao t : this.root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getTransaccoes().values()) {
            AnuncioVenda a = (AnuncioVenda) t.getAnuncio();
            ModoVenda mv = a.getTipoVenda();
            if (!mv.getClass().getSimpleName().equals("Leilao") && t.getComprador().getUsername().equals(Sale_Squared.UTILIZADOR)) {
                res.add(a);
            }

        }

        return res;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lic = new org.jdesktop.swingx.JXTaskPane();
        compras = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        jXTaskPane5 = new org.jdesktop.swingx.JXTaskPane();

        lic.setCollapsed(true);
        lic.setTitle("Licitações");

        compras.setCollapsed(true);
        compras.setTitle("Compras");

        jXTaskPane3.setCollapsed(true);
        jXTaskPane3.setTitle("Vendas");

        jXTaskPane4.setCollapsed(true);
        jXTaskPane4.setTitle("Anúncios Seguidos");

        jXTaskPane5.setCollapsed(true);
        jXTaskPane5.setTitle("Utilizadores Seguidos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lic, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .add(compras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jXTaskPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jXTaskPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jXTaskPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lic, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(compras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jXTaskPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jXTaskPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jXTaskPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTaskPane compras;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane5;
    private org.jdesktop.swingx.JXTaskPane lic;
    // End of variables declaration//GEN-END:variables
}
