/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.AnuncioVenda;
import Business_Layer.Leilao;
import Business_Layer.SaleSquared;
import Presentation_Layer.Sale_Squared;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_Leilao extends javax.swing.JPanel {
    private final Sale_Squared root;
    private final int idanuncio;
    private double vlicmin;
    /**
     * Creates new form Anuncio_Leilao2
     */
    
    public Anuncio_Leilao(final Sale_Squared root, int idanuncio) {
        initComponents();
        this.root = root;
        this.idanuncio = idanuncio;
        
        Leilao l = (Leilao) ((AnuncioVenda)root.getSistema().encontrarAnuncio(idanuncio)).getTipoVenda();
        licatual.setText("€ "+l.getPrecoActual());
        vlicmin = l.getPrecoActual()+l.getIncrementoMinimo();
        licmin.setText("(Tem que licitar €" + vlicmin +" para cima)");
        
		
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        licmac = new javax.swing.JTextField();
        licitacao = new javax.swing.JButton();
        licmin = new javax.swing.JLabel();
        licatual = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Licitação Atual:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Licitação Máxima:   €");

        licitacao.setText("Licitar");
        licitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licitacaoActionPerformed(evt);
            }
        });

        licmin.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        licmin.setText("jLabel3");

        licatual.setText("jLabel4");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(licatual))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(licmin)
                            .add(layout.createSequentialGroup()
                                .add(licmac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(licitacao))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(licatual))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(licmac, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(licitacao))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(licmin)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void licitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licitacaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel licatual;
    private javax.swing.JButton licitacao;
    private javax.swing.JTextField licmac;
    private javax.swing.JLabel licmin;
    // End of variables declaration//GEN-END:variables
}
