/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Business_Layer.AnuncioVenda;
import Presentation_Layer.Sale_Squared;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_NovaCompra1 extends javax.swing.JPanel {

    /**
     * Creates new form Anuncio_NovaCompra1
     */
    private Map<String, JRadioButton> pagamentos;
    private final int idanuncio;
    private final Sale_Squared root;
    private final AnuncioVenda anuncio;
    private final Icon certo = new ImageIcon(getClass().getResource("/Imagens/certo.png"));
    private final Icon errado = new ImageIcon(getClass().getResource("/Imagens/errado.png"));
    
    public Anuncio_NovaCompra1(final Sale_Squared root, int idanuncio) {
        initComponents();
        this.idanuncio = idanuncio;
        this.root = root;
        this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(idanuncio);
        pagamentos = new HashMap<>();
        pagamentos.put(paypal.getText(), paypal);
        pagamentos.put(jRadioButton5.getText(), jRadioButton5);
        pagamentos.put(dinheiro.getText(), dinheiro);
        pagamentos.put(transf.getText(), transf);
        pagamentos.put(enviocob.getText(), enviocob);

        for (String s : pagamentos.keySet()) {
            buttonGroup1.add(pagamentos.get(s));
            if (!anuncio.getModosPagamento().contains(s)) {
                pagamentos.get(s).setEnabled(false);
            } else {
                buttonGroup1.clearSelection();
                pagamentos.get(s).setSelected(true);
            }
        }

        this.jSpinner1.setModel(new SpinnerNumberModel(1, 1, anuncio.getQuantidade(), 1));

        buttonGroup2.add(novamorada);
        buttonGroup2.add(moradaperfil);
        jPanel1.setVisible(false);
        moradaperfil.setSelected(true);
        mv.setVisible(false);
        cpv.setVisible(false);
        lv.setVisible(false);

    }

    public String getPagamento() {
        String res = null;
        for (String s : pagamentos.keySet()) {
            if (pagamentos.get(s).isSelected()) {
                res = s;
                break;
            }
        }
        return res;
    }

    public int getQuantidade() {
        return (int) jSpinner1.getValue();
    }

    public boolean getMoradaPerfil() {
        return this.moradaperfil.isSelected();
    }

    public String getPais() {
        return (String) pais.getSelectedItem();
    }

    public String getMorada() throws Exception {
        String smorada = morada.getText();
        mv.setVisible(true);
        if (smorada.isEmpty()) {
            mv.setIcon(errado);
            throw new Exception("Insira uma morada");
        }
        if (smorada.length() > 49) {
            mv.setIcon(errado);
            throw new Exception("Insira uma morada com menos de 50 caracteres");
        }
        mv.setIcon(certo);
        return smorada;

    }

    public String getLocalidade() throws Exception {
        String sloc = morada.getText();
        lv.setVisible(true);
        if (sloc.isEmpty()) {
            lv.setIcon(errado);
            throw new Exception("Insira uma Localidade");
        }
        if (sloc.length() > 29) {
            lv.setIcon(errado);
            throw new Exception("Insira uma Localidade com menos de 30 caracteres");
        }
        lv.setIcon(certo);
        return sloc;

    }

    public String getCodPostal() throws Exception {
        String scp1 = cp1.getText();
        String scp2 = cp2.getText();
        cpv.setVisible(true);
        if (scp1.isEmpty() || scp2.isEmpty() || scp1.length() > 4 || scp2.length() > 3) {
            cpv.setIcon(errado);
            throw new Exception("Insira um Código Postal válido");
        }
        cpv.setIcon(certo);
        return scp1 + "-" + scp2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        paypal = new javax.swing.JRadioButton();
        enviocob = new javax.swing.JRadioButton();
        transf = new javax.swing.JRadioButton();
        dinheiro = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        moradaperfil = new javax.swing.JRadioButton();
        novamorada = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pais = new javax.swing.JComboBox();
        morada = new org.jdesktop.swingx.JXTextField();
        cp1 = new org.jdesktop.swingx.JXTextField();
        jLabel9 = new javax.swing.JLabel();
        cp2 = new org.jdesktop.swingx.JXTextField();
        loc = new org.jdesktop.swingx.JXTextField();
        mv = new javax.swing.JLabel();
        lv = new javax.swing.JLabel();
        cpv = new javax.swing.JLabel();

        paypal.setText("Paypal");

        enviocob.setText("Envio à cobrança");
        enviocob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviocobActionPerformed(evt);
            }
        });

        transf.setText("Transferência Bancária");

        dinheiro.setText("Dinheiro");

        jRadioButton5.setText("Cheque");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel2.setText("Pagamento");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel4.setText("Morada");

        moradaperfil.setText("Morada do perfil");
        moradaperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moradaperfilActionPerformed(evt);
            }
        });

        novamorada.setText("Alterar morada de entrega");
        novamorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novamoradaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("País");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Morada");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Código Postal");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setText("Localidade");

        pais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        morada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                moradaFocusLost(evt);
            }
        });

        cp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cp1FocusLost(evt);
            }
        });

        jLabel9.setText("-");

        cp2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cp2FocusLost(evt);
            }
        });

        loc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                locFocusLost(evt);
            }
        });

        mv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/certo.png"))); // NOI18N

        lv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/certo.png"))); // NOI18N

        cpv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/certo.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(cp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cp2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cpv)
                                .add(0, 38, Short.MAX_VALUE))
                            .add(loc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel6))
                        .add(56, 56, 56)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(pais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(morada, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .add(6, 6, 6)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mv)
                    .add(lv)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(pais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(morada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mv))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel7)
                        .add(cp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel9)
                        .add(cp2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(cpv))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lv)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel8)
                        .add(loc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dinheiro)
                            .add(paypal))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(enviocob)
                                .add(4, 4, 4)
                                .add(transf))
                            .add(jRadioButton5)))
                    .add(layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel4)
                    .add(moradaperfil)
                    .add(novamorada)
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(paypal)
                    .add(enviocob)
                    .add(transf))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dinheiro)
                    .add(jRadioButton5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jSpinner1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(moradaperfil)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(novamorada)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enviocobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviocobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviocobActionPerformed

    private void novamoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novamoradaActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        if (!this.anuncio.isEnvioEstrangeiro()) {
            pais.setVisible(false);
            jLabel5.setVisible(false);
        }



    }//GEN-LAST:event_novamoradaActionPerformed

    private void moradaperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moradaperfilActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
    }//GEN-LAST:event_moradaperfilActionPerformed

    private void moradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_moradaFocusLost
        try {
            // TODO add your handling code here:
            getMorada();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_moradaFocusLost

    private void cp1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cp1FocusLost
        // TODO add your handling code here:
        try {
            getCodPostal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cp1FocusLost

    private void cp2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cp2FocusLost
        // TODO add your handling code here:
          try {
            getCodPostal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cp2FocusLost

    private void locFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locFocusLost
        // TODO add your handling code here:
        try {
            getLocalidade();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_locFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.jdesktop.swingx.JXTextField cp1;
    private org.jdesktop.swingx.JXTextField cp2;
    private javax.swing.JLabel cpv;
    private javax.swing.JRadioButton dinheiro;
    private javax.swing.JRadioButton enviocob;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSpinner jSpinner1;
    private org.jdesktop.swingx.JXTextField loc;
    private javax.swing.JLabel lv;
    private org.jdesktop.swingx.JXTextField morada;
    private javax.swing.JRadioButton moradaperfil;
    private javax.swing.JLabel mv;
    private javax.swing.JRadioButton novamorada;
    private javax.swing.JComboBox pais;
    private javax.swing.JRadioButton paypal;
    private javax.swing.JRadioButton transf;
    // End of variables declaration//GEN-END:variables
}
