/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Presentation_Layer.Sale_Squared;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_NovaCompra extends javax.swing.JDialog {

    /**
     * Creates new form Anuncio_NovaCompra
     */
    private Anuncio_NovaCompra1 step1;
    private Anuncio_NovaCompra2 step2;
    int step;
    private final int idanuncio;
    private final Sale_Squared root;
    private final Anuncio anuncio;

    public Anuncio_NovaCompra(final Sale_Squared root, int idanuncio) {
        super(root, true);
        initComponents();
        this.idanuncio = idanuncio;
        this.root = root;
        this.anuncio = this.root.getSistema().encontrarAnuncio(idanuncio);
        step = 1;
        step1 = new Anuncio_NovaCompra1(root, idanuncio);
        step2 = new Anuncio_NovaCompra2();
        stepChange();


    }

    private void stepChange() {
        jPanel2.removeAll();

        switch (step) {
            case 1: {
                jPanel2.add(step1,"1");
                voltar.setVisible(false);
                next.setText("Seguinte");
                break;
            }
            case 2: {
                jPanel2.add(step2,"2");
                voltar.setVisible(true);
                next.setText("Confirmar");
                break;
            }
        }
        jPanel2.updateUI();
        jPanel2.validate();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setText("Nova proposta de compra");

        jPanel2.setLayout(new java.awt.CardLayout());

        next.setText("Seguinte");

        voltar.setText("Voltar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(0, 227, Short.MAX_VALUE))
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(voltar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(next)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(next)
                    .add(voltar))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
