/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Business_Layer.AnuncioVenda;
import Business_Layer.Transaccao;
import Presentation_Layer.Registo.Registo_Main;
import Presentation_Layer.Sale_Squared;
import javax.swing.JDialog;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_Compra extends javax.swing.JPanel {

    private final Sale_Squared root;
    private final int idanuncio;
    private final AnuncioVenda anuncio;

    /**
     * Creates new form Anuncio_Compra2
     */
    public Anuncio_Compra(final Sale_Squared root, int idanuncio) {
        initComponents();
        this.root = root;
        this.idanuncio = idanuncio;
        this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(idanuncio);
        this.preco.setText("€ " + anuncio.getPreco());
        this.troca.setText("Este utilizador " + (anuncio.getPossivelTrocar() ? "" : "não ") + "aceita trocas");
        if (anuncio.getAnunciante().getUsername().equals(Sale_Squared.UTILIZADOR)) {
            jButton1.setEnabled(false);
        } else {
            for (Transaccao t : anuncio.getAnunciante().getTransaccoes().values()) {
                if (t.getComprador().getUsername().equals(Sale_Squared.UTILIZADOR))
                {
                    jButton1.setEnabled(false);
                    break;
                }
            }
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        troca = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Preço:");

        preco.setText("jLabel2");

        troca.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        troca.setText("jLabel2");

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(troca)
                    .add(layout.createSequentialGroup()
                        .add(preco)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(preco)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(troca))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (Sale_Squared.REGISTADO) {
            
            JDialog frame = new Anuncio_NovaCompra(root, idanuncio,Anuncio_NovaCompra.VENDA);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
        } else {
            root.setBody(new Registo_Main(root), "Novo Registo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel troca;
    // End of variables declaration//GEN-END:variables

  
}
