/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Business_Layer.AnuncioVenda;
import Business_Layer.ModoVenda;
import Business_Layer.Transaccao;
import Business_Layer.UtilizadorRegistado;
import Presentation_Layer.Perfil.Perfil;
import Presentation_Layer.Sale_Squared;
import java.util.GregorianCalendar;
import java.util.Map;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_Info extends javax.swing.JPanel {

    private final Sale_Squared root;
    private final int idanuncio;
    private final AnuncioVenda anuncio;
    private final String username;

    /**
     * Creates new form Anuncio_Info2
     */
    public Anuncio_Info(final Sale_Squared root, int idanuncio) {
        initComponents();
        this.root = root;
        this.idanuncio = idanuncio;
        this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(this.idanuncio);
        this.username = this.anuncio.getAnunciante().getUsername();

        inicio.setText(showdata(anuncio.getDataInser()));
        fim.setText(temporestante(new GregorianCalendar(), anuncio.getDataExpir()) + " (" + showdata(anuncio.getDataExpir()) + ")");
        quantidade.setText("" + anuncio.getQuantidade());

        envioEst.setText("(Envio para o estrangeiro: " + (anuncio.isEnvioEstrangeiro() ? "Sim" : "Não"));
        String codPostal = this.root.getSistema().encontrarUtilizadorReg(username).getCodPostal();
        String localidade = this.root.getSistema().encontrarUtilizadorReg(username).getLocalidade();
        seguir.setVisible(Sale_Squared.REGISTADO);
        reportar.setVisible(Sale_Squared.REGISTADO);
        if (Sale_Squared.REGISTADO) {
            Map<Integer, Anuncio> anunciosseguidos = root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getAnuncSeguidos();
            if (anunciosseguidos.containsKey(new Integer(this.idanuncio))) {
                seguir.setText("Deixar Anúncio");
            }
        }
        loc.setText(codPostal + ", " + localidade);
        user.setText(username);
        estado.setText((this.anuncio.isEstadoProduto() == AnuncioVenda.NOVO) ? "Novo" : "Usado");

       
            ModoVenda mv = anuncio.getTipoVenda();
            if (mv.getClass().getSimpleName().equals("Leilao")) {
                jPanel1.add(new Anuncio_Leilao(root, this.anuncio));
            } else {
               
                jPanel1.add(new Anuncio_Compra(root, idanuncio));

            }

        


    }

    private String showdata(GregorianCalendar gc) {
        int dia, mes, ano, hora, minutos;

        dia = gc.get(GregorianCalendar.DAY_OF_MONTH);
        mes = gc.get(GregorianCalendar.MONTH) + 1;
        ano = gc.get(GregorianCalendar.YEAR);
        hora = gc.get(GregorianCalendar.HOUR_OF_DAY);
        minutos = gc.get(GregorianCalendar.MINUTE);
        return dia + "/" + mes + "/" + ano + " - " + hora + ":" + minutos;
    }

    private String temporestante(GregorianCalendar in, GregorianCalendar end) {

        long lin = in.getTimeInMillis();
        long lend = end.getTimeInMillis();
        long diff = lend - lin;
        long segundos = diff / 1000;
        long msres = diff % 1000;

        long minutos = segundos / 60;
        long sres = segundos % 60;

        long horas = minutos / 60;
        long mres = minutos % 60;

        long ldia = horas / 24;
        long hres = horas % 24;

        int dia = (int) ldia;
        int hora = (int) hres;
        int minuto = (int) mres;
        int segundo = (int) sres;

        String sdias = (dia > 0) ? (dia > 1 ? dia + " dias " : "1 dia ") : "";
        String shoras = (hora > 0) ? (hora > 1 ? hora + " horas " : "1 hora ") : "";
        String sminutos = (minuto > 0) ? (minuto > 1 ? minuto + " minutos " : "1 minuto ") : "";
        String ssegundos = (segundo > 0) ? (segundo > 1 ? segundo + " segundos" : "1 segundo ") : "";
        if ((sdias + shoras + sminutos + ssegundos + "").isEmpty()) {
            return "Terminado";
        } else {
            return sdias + ", " + shoras + " " + sminutos + " " + ssegundos;
        }




    }

    public void removerSeguir() {


        if (seguir.getText().equals("Seguir Anúncio")) {
            seguir.setText("Seguir Anúncio");
            root.getSistema().seguirAnuncio(Sale_Squared.UTILIZADOR, root.getSistema().encontrarAnuncio(this.idanuncio));
        } else {
            seguir.setText("Seguir Anúncio");
            root.getSistema().deixarSegAnuncio(Sale_Squared.UTILIZADOR, this.idanuncio);
        }






    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        fim = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        perfil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        seguir = new javax.swing.JButton();
        reportar = new javax.swing.JButton();
        envioEst = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Início:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Fim:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Quantidade:");

        inicio.setText("jLabel4");

        fim.setText("jLabel5");

        quantidade.setText("jLabel6");

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Utilizador:");

        user.setText("jLabel4");

        perfil.setText("Ver Perfil");
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Localidade:");

        loc.setText("jLabel4");

        seguir.setText("Seguir Anúncio");
        seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirActionPerformed(evt);
            }
        });

        reportar.setText("Reportar");
        reportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportarActionPerformed(evt);
            }
        });

        envioEst.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        envioEst.setText("jLabel4");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Estado:");

        estado.setText("jLabel4");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(user)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(perfil))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(inicio)
                                    .add(fim)
                                    .add(quantidade)))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(reportar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel9)
                                        .add(jLabel10))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(estado)
                                        .add(envioEst)
                                        .add(loc)
                                        .add(seguir)))))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(inicio))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(fim))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(quantidade))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(user)
                    .add(perfil))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(loc))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(envioEst)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(estado))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(seguir)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(reportar)
                .add(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        // TODO add your handling code here:
        root.setBody(new Perfil(root, username), username);

    }//GEN-LAST:event_perfilActionPerformed

    private void seguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirActionPerformed
        // TODO add your handling code here:
        removerSeguir();
    }//GEN-LAST:event_seguirActionPerformed

    private void reportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel envioEst;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fim;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loc;
    private javax.swing.JButton perfil;
    private javax.swing.JLabel quantidade;
    private javax.swing.JButton reportar;
    private javax.swing.JButton seguir;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
