/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Business_Layer.Imagem;
import Presentation_Layer.Sale_Squared;
import Presentation_Layer.Tabbed.Tabbed_Anuncio;
import Presentation_Layer.Tabbed.Tabbed_Sugestoes;
import java.util.List;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_Main extends javax.swing.JPanel {

    private final int idanuncio;
    private final Anuncio anuncio;
    private final ImagePanel imagepanel;

    /**
     * Creates new form Anuncio_Main2
     */
    public Anuncio_Main(final Sale_Squared root, int idAnuncio) {
        initComponents();
        this.idanuncio = idAnuncio;
        this.anuncio = root.getSistema().encontrarAnuncio(this.idanuncio);
        
        this.titulo.setText(this.anuncio.getTitulo());
        imagepanel = new ImagePanel();

        this.imagem.add(imagepanel,"Imagem");
        this.info.add(new Tabbed_Anuncio(root, idanuncio, imagepanel),"Info");
        this.compra.add(new Anuncio_Info(root, idanuncio),"Compra");
        this.sugestoes.add(new Tabbed_Sugestoes(root, idanuncio),"Sugestoes");
        
        if (!this.anuncio.getImagens().isEmpty()) {
            List<Imagem> imagens = (List<Imagem>) this.anuncio.getImagens().values();
            this.imagepanel.setImage(imagens.get(0));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        imagem = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        compra = new javax.swing.JPanel();
        sugestoes = new javax.swing.JPanel();

        titulo.setFont(new java.awt.Font("Lucida Grande", 1, 35)); // NOI18N
        titulo.setText("jLabel1");

        imagem.setLayout(new java.awt.CardLayout());

        info.setLayout(new java.awt.CardLayout());

        compra.setLayout(new java.awt.CardLayout());

        sugestoes.setLayout(new java.awt.CardLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(titulo)
                    .add(layout.createSequentialGroup()
                        .add(imagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(compra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(info, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sugestoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .add(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(titulo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(imagem, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(48, 48, 48)
                        .add(compra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(info, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .add(sugestoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel compra;
    private javax.swing.JPanel imagem;
    private javax.swing.JPanel info;
    private javax.swing.JPanel sugestoes;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
