/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Anuncio;

import Business_Layer.Anuncio;
import Business_Layer.AnuncioVenda;
import Business_Layer.Transaccao;
import Presentation_Layer.Sale_Squared;
import java.util.GregorianCalendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import sun.util.calendar.Gregorian;

/**
 *
 * @author ricardobranco
 */
public class Anuncio_NovaCompra extends javax.swing.JDialog {

    /**
     * Creates new form Anuncio_NovaCompra
     */
    private Anuncio_NovaCompra1 step1;
    private Anuncio_NovaCompra2 step2;
    int step;
    private final int idanuncio;
    private final Sale_Squared root;
    private AnuncioVenda anuncio;
    private Transaccao t;

    public Anuncio_NovaCompra(final Sale_Squared root, int idanuncio) {
        super(root, true);
        initComponents();
        this.idanuncio = idanuncio;
        this.root = root;
        this.anuncio = (AnuncioVenda) this.root.getSistema().encontrarAnuncio(idanuncio);
        step = 1;
        step1 = new Anuncio_NovaCompra1(root, idanuncio);
        jPanel1.add(step1, "1");
        pack();



    }

    private void stepChange() {
        jPanel1.removeAll();
        switch (step) {
            case 1: {

                jPanel1.add(step1, "1");
                voltar.setVisible(false);
                next.setText("Seguinte");
                break;
            }
            case 2: {
                try {
                    double preco = this.anuncio.getPreco();
                    double seguro = this.anuncio.getSeguro();
                    double portes = this.anuncio.getPrecoEnvio();
                    int quantidade = step1.getQuantidade();
                    String pais = step1.getMoradaPerfil() ? root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getPais() : this.anuncio.isEnvioEstrangeiro() ? step1.getPais() : root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getPais();
                    String localidade = step1.getMoradaPerfil() ? root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getLocalidade() : step1.getLocalidade();
                    String cp = step1.getMoradaPerfil() ? root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getCodPostal() : step1.getCodPostal();
                    String morada = step1.getMoradaPerfil() ? root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).getMorada() : step1.getMorada();
                    String pagamento = step1.getPagamento();
                    step2 = new Anuncio_NovaCompra2(preco, quantidade, seguro, portes, pagamento, pais, cp, morada, localidade);
                    this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(idanuncio);
                    this.t = new Transaccao(anuncio, anuncio.getAnunciante(), root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR), root.getSistema().registaIdTransac(),
                            new GregorianCalendar(), step2.getVTotal(), step1.getPagamento(), morada, cp, localidade, pais, Transaccao.EU_AGUARDAR_ACEITACAO, quantidade);
                } catch (Exception e) {
                    e.printStackTrace();
                    String html1 = "<html><body style='width: ";
                    String html2 = "Dados Invalidos";
                    JOptionPane.showMessageDialog(this, new JLabel(html1 + "300" + html2 + e.getMessage()), html2, WIDTH, new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sem_Imagem.png")));

                }

                jPanel1.add(step2, "2");
                voltar.setVisible(true);
                next.setText("Confirmar");
                break;
            }
        }
        jPanel1.updateUI();
        jPanel1.validate();
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel1.setText("Nova proposta de compra");

        next.setText("Seguinte");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(voltar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(next))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(voltar)
                    .add(next))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try {
            switch (step) {
                case 1: {
                    step = 2;
                    stepChange();
                    break;
                }
                case 2: {
                    this.root.getSistema().encontrarAnuncio(idanuncio).getAnunciante().inserirTransaccao(t);
                    this.root.getSistema().encontrarUtilizadorReg(Sale_Squared.UTILIZADOR).inserirTransaccao(t);
                    String html1 = "<html><body style='width: ";
                    String html2 = "";
                    JOptionPane.showMessageDialog(this, new JLabel(html1 + "300" + html2 + "Proposta de compra efectuada com êxito"), html2, WIDTH, new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sem_Imagem.png")));
                    root.setBody(new Anuncio_Main(root, idanuncio), root.getSistema().encontrarAnuncio(idanuncio).getTitulo());
                    dispose();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            String html1 = "<html><body style='width: ";
            String html2 = "Dados Invalidos";
            JOptionPane.showMessageDialog(this, new JLabel(html1 + "300" + html2 + e.getMessage()), html2, WIDTH, new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sem_Imagem.png")));

        }


    }//GEN-LAST:event_nextActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        step = 1;
        stepChange();
    }//GEN-LAST:event_voltarActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
