/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Componentes;

import Business_Layer.AnuncioVenda;
import Business_Layer.Imagem;
import Business_Layer.Leilao;
import Business_Layer.ModoVenda;
import Business_Layer.VendaDirecta;
import Presentation_Layer.Anuncio.Anuncio_Main;
import Presentation_Layer.Sale_Squared;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ricardobranco
 */
public class Produto_Base extends javax.swing.JPanel {

    private final Sale_Squared root;
    private final int idanuncio;
    private AnuncioVenda anuncio;

    /**
     * Creates new form Produto_Base
     */
    public Produto_Base(final Sale_Squared root, int idanuncio) {
        initComponents();
        this.root = root;
        this.idanuncio = idanuncio;
        this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(this.idanuncio);

        List<Imagem> ci = (List<Imagem>) anuncio.getImagens().values();
        if (!ci.isEmpty()) {
            thumb.setIcon(new Avatar(new ImageIcon(ci.get(0).getPath()).getImage()));
        }

        ModoVenda mv = anuncio.getTipoVenda();
        boolean leilao = mv.getClass().getSimpleName().equals("Leilao");
        if (leilao) {
            preco.setText("€ " + ((Leilao) mv).getPrecoActual());
        } else {
            preco.setText("€ " + ((VendaDirecta) mv).getPreco());
        }
        jXHyperlink1.setText(anuncio.getTitulo());
        tempo.setText(temporestante(new GregorianCalendar(), this.anuncio.getDataExpir()));
    }

    private String temporestante(GregorianCalendar in, GregorianCalendar end) {

        long lin = in.getTimeInMillis();
        long lend = end.getTimeInMillis();
        long diff = lend - lin;
        long segundos = diff / 1000;

        long minutos = segundos / 60;
        long sres = segundos % 60;

        long horas = minutos / 60;
        long mres = minutos % 60;

        long ldia = horas / 24;
        long hres = horas % 24;

        int dia = (int) ldia;
        int hora = (int) hres;
        int minuto = (int) mres;
        int segundo = (int) sres;

        String sdias = (dia > 0) ? (dia > 1 ? dia + " dias " : "1 dia ") : "";
        String shoras = (hora > 0) ? (hora > 1 ? hora + " horas " : "1 hora ") : "";
        String sminutos = (minuto > 0) ? (minuto > 1 ? minuto + " minutos " : "1 minuto ") : "";
        String ssegundos = (segundo > 0) ? (segundo > 1 ? segundo + " segundos" : "1 segundo ") : "";
        if ((sdias + shoras + sminutos + ssegundos + "").isEmpty()) {
            return "Terminado";
        } else {
            return sdias + ", " + shoras + " " + sminutos + " " + ssegundos;
        }




    }

    public void abrir() {
        this.anuncio = (AnuncioVenda) root.getSistema().encontrarAnuncio(idanuncio);
        JPanel anuncio = new Anuncio_Main(root, this.idanuncio);

        root.setBody(anuncio, this.anuncio.getTitulo());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thumb = new javax.swing.JButton();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        preco = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();

        thumb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sem_Imagem.png"))); // NOI18N
        thumb.setContentAreaFilled(false);
        thumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thumbActionPerformed(evt);
            }
        });

        jXHyperlink1.setForeground(new java.awt.Color(0, 102, 204));
        jXHyperlink1.setText("jXHyperlink1");
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });

        preco.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        preco.setText("jLabel1");

        tempo.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        tempo.setText("jLabel2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(thumb)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tempo))
                        .addContainerGap(109, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(preco)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jXHyperlink1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(preco)
                        .add(2, 2, 2)
                        .add(tempo))
                    .add(thumb))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void thumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thumbActionPerformed
        // TODO add your handling code here:
        abrir();
    }//GEN-LAST:event_thumbActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel tempo;
    private javax.swing.JButton thumb;
    // End of variables declaration//GEN-END:variables
}
