/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Home;

import Business_Layer.Anuncio;
import Presentation_Layer.Pesquisa.Pesquisa_Resultado;
import Presentation_Layer.Sale_Squared;
import java.util.Set;

/**
 *
 * @author ricardobranco
 */
public class Categorias extends javax.swing.JPanel {

    private final Sale_Squared root;

    /**
     * Creates new form Categorias2
     */
    public Categorias(final Sale_Squared root) {
        initComponents();
        this.root = root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHyperlink32 = new org.jdesktop.swingx.JXHyperlink();
        jPanel4 = new javax.swing.JPanel();
        fitness = new org.jdesktop.swingx.JXHyperlink();
        brinquedos = new org.jdesktop.swingx.JXHyperlink();
        caca_pesca = new org.jdesktop.swingx.JXHyperlink();
        musica = new org.jdesktop.swingx.JXHyperlink();
        filmes = new org.jdesktop.swingx.JXHyperlink();
        natacao = new org.jdesktop.swingx.JXHyperlink();
        futebol = new org.jdesktop.swingx.JXHyperlink();
        campismo = new org.jdesktop.swingx.JXHyperlink();
        desporto_entret = new org.jdesktop.swingx.JXHyperlink();
        jPanel1 = new javax.swing.JPanel();
        pecas_auto = new org.jdesktop.swingx.JXHyperlink();
        auto = new org.jdesktop.swingx.JXHyperlink();
        banda_desenhada = new org.jdesktop.swingx.JXHyperlink();
        manuais_escolares = new org.jdesktop.swingx.JXHyperlink();
        revistas = new org.jdesktop.swingx.JXHyperlink();
        livros_revistas = new org.jdesktop.swingx.JXHyperlink();
        veiculos = new org.jdesktop.swingx.JXHyperlink();
        literatura_infantil = new org.jdesktop.swingx.JXHyperlink();
        literatura = new org.jdesktop.swingx.JXHyperlink();
        jPanel2 = new javax.swing.JPanel();
        mobilia = new org.jdesktop.swingx.JXHyperlink();
        plantas_flores = new org.jdesktop.swingx.JXHyperlink();
        imovies = new org.jdesktop.swingx.JXHyperlink();
        jardinagem = new org.jdesktop.swingx.JXHyperlink();
        casa_jardim = new org.jdesktop.swingx.JXHyperlink();
        animais = new org.jdesktop.swingx.JXHyperlink();
        saude = new org.jdesktop.swingx.JXHyperlink();
        cosméticos = new org.jdesktop.swingx.JXHyperlink();
        higiene = new org.jdesktop.swingx.JXHyperlink();
        jPanel3 = new javax.swing.JPanel();
        vestuario = new org.jdesktop.swingx.JXHyperlink();
        acessorios = new org.jdesktop.swingx.JXHyperlink();
        antiguidades = new org.jdesktop.swingx.JXHyperlink();
        moda = new org.jdesktop.swingx.JXHyperlink();
        medalhas = new org.jdesktop.swingx.JXHyperlink();
        moedas_notas = new org.jdesktop.swingx.JXHyperlink();
        selos = new org.jdesktop.swingx.JXHyperlink();
        colec_arte = new org.jdesktop.swingx.JXHyperlink();
        arte = new org.jdesktop.swingx.JXHyperlink();
        jPanel5 = new javax.swing.JPanel();
        audiotv = new org.jdesktop.swingx.JXHyperlink();
        consolas = new org.jdesktop.swingx.JXHyperlink();
        fotografia = new org.jdesktop.swingx.JXHyperlink();
        informatica = new org.jdesktop.swingx.JXHyperlink();
        telemoveis = new org.jdesktop.swingx.JXHyperlink();
        gad = new org.jdesktop.swingx.JXHyperlink();
        circuitos = new org.jdesktop.swingx.JXHyperlink();
        tec_eletro = new org.jdesktop.swingx.JXHyperlink();
        outros = new org.jdesktop.swingx.JXHyperlink();

        jXHyperlink32.setForeground(new java.awt.Color(0, 108, 204));
        jXHyperlink32.setText("Mobília");

        fitness.setForeground(new java.awt.Color(0, 108, 204));
        fitness.setText("Fitness e Musculação");
        fitness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnessActionPerformed(evt);
            }
        });

        brinquedos.setForeground(new java.awt.Color(0, 108, 204));
        brinquedos.setText("Brinquedos");
        brinquedos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brinquedosActionPerformed(evt);
            }
        });

        caca_pesca.setForeground(new java.awt.Color(0, 108, 204));
        caca_pesca.setText("Caça e Pesca");
        caca_pesca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caca_pescaActionPerformed(evt);
            }
        });

        musica.setForeground(new java.awt.Color(0, 108, 204));
        musica.setText("Música");
        musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaActionPerformed(evt);
            }
        });

        filmes.setForeground(new java.awt.Color(0, 108, 204));
        filmes.setText("Filmes e Cinema");
        filmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmesActionPerformed(evt);
            }
        });

        natacao.setForeground(new java.awt.Color(0, 108, 204));
        natacao.setText("Natação");
        natacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natacaoActionPerformed(evt);
            }
        });

        futebol.setForeground(new java.awt.Color(0, 108, 204));
        futebol.setText("Futebol");
        futebol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futebolActionPerformed(evt);
            }
        });

        campismo.setForeground(new java.awt.Color(0, 108, 204));
        campismo.setText("Campismo");
        campismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campismoActionPerformed(evt);
            }
        });

        desporto_entret.setForeground(new java.awt.Color(0, 108, 204));
        desporto_entret.setText("Desporto e Entretenimento");
        desporto_entret.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        desporto_entret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desporto_entretActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(brinquedos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(fitness, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, filmes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, musica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, caca_pesca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, campismo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, futebol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, natacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(desporto_entret, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(desporto_entret, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(brinquedos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fitness, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(filmes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(musica, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(caca_pesca, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(campismo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(futebol, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(natacao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pecas_auto.setForeground(new java.awt.Color(0, 108, 204));
        pecas_auto.setText("Peças Auto");
        pecas_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pecas_autoActionPerformed(evt);
            }
        });

        auto.setForeground(new java.awt.Color(0, 108, 204));
        auto.setText("Auto");
        auto.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });

        banda_desenhada.setForeground(new java.awt.Color(0, 108, 204));
        banda_desenhada.setText("Banda Desenhada");
        banda_desenhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banda_desenhadaActionPerformed(evt);
            }
        });

        manuais_escolares.setForeground(new java.awt.Color(0, 108, 204));
        manuais_escolares.setText("Manuais Escolares");
        manuais_escolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuais_escolaresActionPerformed(evt);
            }
        });

        revistas.setForeground(new java.awt.Color(0, 108, 204));
        revistas.setText("Revistas");
        revistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revistasActionPerformed(evt);
            }
        });

        livros_revistas.setForeground(new java.awt.Color(0, 108, 204));
        livros_revistas.setText("Livros e Revistas");
        livros_revistas.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        livros_revistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livros_revistasActionPerformed(evt);
            }
        });

        veiculos.setForeground(new java.awt.Color(0, 108, 204));
        veiculos.setText("Veículos");
        veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculosActionPerformed(evt);
            }
        });

        literatura_infantil.setForeground(new java.awt.Color(0, 108, 204));
        literatura_infantil.setText("Literatura Infantil");
        literatura_infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literatura_infantilActionPerformed(evt);
            }
        });

        literatura.setForeground(new java.awt.Color(0, 108, 204));
        literatura.setText("Literatura");
        literatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literaturaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(auto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(livros_revistas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(veiculos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(pecas_auto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(manuais_escolares, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(revistas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(literatura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(literatura_infantil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(banda_desenhada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(auto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pecas_auto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(veiculos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(livros_revistas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(revistas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(manuais_escolares, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(literatura, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(3, 3, 3)
                .add(literatura_infantil, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(banda_desenhada, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mobilia.setForeground(new java.awt.Color(0, 108, 204));
        mobilia.setText("Mobília");
        mobilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiliaActionPerformed(evt);
            }
        });

        plantas_flores.setForeground(new java.awt.Color(0, 108, 204));
        plantas_flores.setText("Plantas e Flores");
        plantas_flores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantas_floresActionPerformed(evt);
            }
        });

        imovies.setForeground(new java.awt.Color(0, 108, 204));
        imovies.setText("Imóveis");
        imovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imoviesActionPerformed(evt);
            }
        });

        jardinagem.setForeground(new java.awt.Color(0, 108, 204));
        jardinagem.setText("Jardinagem");
        jardinagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jardinagemActionPerformed(evt);
            }
        });

        casa_jardim.setForeground(new java.awt.Color(0, 108, 204));
        casa_jardim.setText("Casa e Jardim");
        casa_jardim.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        casa_jardim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa_jardimActionPerformed(evt);
            }
        });

        animais.setForeground(new java.awt.Color(0, 108, 204));
        animais.setText("Animais");
        animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animaisActionPerformed(evt);
            }
        });

        saude.setForeground(new java.awt.Color(0, 108, 204));
        saude.setText("Saúde");
        saude.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        saude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saudeActionPerformed(evt);
            }
        });

        cosméticos.setForeground(new java.awt.Color(0, 108, 204));
        cosméticos.setText("Cosméticos");
        cosméticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosméticosActionPerformed(evt);
            }
        });

        higiene.setForeground(new java.awt.Color(0, 108, 204));
        higiene.setText("Higiene");
        higiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higieneActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(animais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jardinagem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(imovies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mobilia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(plantas_flores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(casa_jardim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saude, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cosméticos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(higiene, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(casa_jardim, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(animais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jardinagem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(imovies, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mobilia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(plantas_flores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(saude, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(higiene, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cosméticos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vestuario.setForeground(new java.awt.Color(0, 108, 204));
        vestuario.setText("Vestuário");
        vestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vestuarioActionPerformed(evt);
            }
        });

        acessorios.setForeground(new java.awt.Color(0, 108, 204));
        acessorios.setText("Acessórios");
        acessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessoriosActionPerformed(evt);
            }
        });

        antiguidades.setForeground(new java.awt.Color(0, 108, 204));
        antiguidades.setText("Antiguidades");
        antiguidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiguidadesActionPerformed(evt);
            }
        });

        moda.setForeground(new java.awt.Color(0, 108, 204));
        moda.setText("Moda");
        moda.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        moda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modaActionPerformed(evt);
            }
        });

        medalhas.setForeground(new java.awt.Color(0, 108, 204));
        medalhas.setText("Medalhas");
        medalhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medalhasActionPerformed(evt);
            }
        });

        moedas_notas.setForeground(new java.awt.Color(0, 108, 204));
        moedas_notas.setText("Moedas e Notas");
        moedas_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moedas_notasActionPerformed(evt);
            }
        });

        selos.setForeground(new java.awt.Color(0, 108, 204));
        selos.setText("Selos");
        selos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selosActionPerformed(evt);
            }
        });

        colec_arte.setForeground(new java.awt.Color(0, 108, 204));
        colec_arte.setText("Coleccionáveis e Arte");
        colec_arte.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        colec_arte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colec_arteActionPerformed(evt);
            }
        });

        arte.setForeground(new java.awt.Color(0, 108, 204));
        arte.setText("Arte");
        arte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(colec_arte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(moda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(moedas_notas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(selos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(medalhas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(antiguidades, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(arte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vestuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(acessorios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(colec_arte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(selos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(moedas_notas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(medalhas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(antiguidades, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(arte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(moda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(vestuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(13, 13, 13)
                .add(acessorios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        audiotv.setForeground(new java.awt.Color(0, 108, 204));
        audiotv.setText("Áudio Tv e Vídeo");
        audiotv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audiotvActionPerformed(evt);
            }
        });

        consolas.setForeground(new java.awt.Color(0, 108, 204));
        consolas.setText("Consolas");
        consolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolasActionPerformed(evt);
            }
        });

        fotografia.setForeground(new java.awt.Color(0, 108, 204));
        fotografia.setText("Fotografia");
        fotografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotografiaActionPerformed(evt);
            }
        });

        informatica.setForeground(new java.awt.Color(0, 108, 204));
        informatica.setText("Informática");
        informatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informaticaActionPerformed(evt);
            }
        });

        telemoveis.setForeground(new java.awt.Color(0, 108, 204));
        telemoveis.setText("Telémoveis e Telefones");
        telemoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telemoveisActionPerformed(evt);
            }
        });

        gad.setForeground(new java.awt.Color(0, 108, 204));
        gad.setText("Gadgets");
        gad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gadActionPerformed(evt);
            }
        });

        circuitos.setForeground(new java.awt.Color(0, 108, 204));
        circuitos.setText("Circuitos");
        circuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuitosActionPerformed(evt);
            }
        });

        tec_eletro.setForeground(new java.awt.Color(0, 108, 204));
        tec_eletro.setText("Tecnologia e Electrónica");
        tec_eletro.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        tec_eletro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tec_eletroActionPerformed(evt);
            }
        });

        outros.setForeground(new java.awt.Color(0, 108, 204));
        outros.setText("Outros");
        outros.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tec_eletro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(outros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, consolas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, fotografia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, informatica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, telemoveis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, gad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, circuitos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, audiotv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(tec_eletro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(audiotv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(consolas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fotografia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(informatica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(telemoveis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(gad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(circuitos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(outros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casa_jardimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa_jardimActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Casa e Jardim"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_casa_jardimActionPerformed

    private void saudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saudeActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Saúde"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_saudeActionPerformed

    private void livros_revistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livros_revistasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Livros e Revistas"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_livros_revistasActionPerformed

    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Auto"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_autoActionPerformed

    private void modaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Moda"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_modaActionPerformed

    private void colec_arteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colec_arteActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Coleccionáveis e Arte"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_colec_arteActionPerformed

    private void desporto_entretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desporto_entretActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Desporto e Entretenimento"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_desporto_entretActionPerformed

    private void tec_eletroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tec_eletroActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Tecnologia e Electrónica"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_tec_eletroActionPerformed

    private void outrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Outros"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_outrosActionPerformed

    private void futebolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futebolActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Futebol"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_futebolActionPerformed

    private void pecas_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pecas_autoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Peças Auto"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_pecas_autoActionPerformed

    private void veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Veículos"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_veiculosActionPerformed

    private void revistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revistasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Revistas"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_revistasActionPerformed

    private void manuais_escolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuais_escolaresActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Manuais Escolares"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_manuais_escolaresActionPerformed

    private void literaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literaturaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Literatura"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_literaturaActionPerformed

    private void literatura_infantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literatura_infantilActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Literatura Infantil"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_literatura_infantilActionPerformed

    private void banda_desenhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banda_desenhadaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Banda Desenhada"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_banda_desenhadaActionPerformed

    private void animaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animaisActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Animais"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_animaisActionPerformed

    private void jardinagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jardinagemActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Jardinagem"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_jardinagemActionPerformed

    private void imoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imoviesActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Imóveis"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_imoviesActionPerformed

    private void mobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiliaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Mobília"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_mobiliaActionPerformed

    private void plantas_floresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantas_floresActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Plantas e Flores"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_plantas_floresActionPerformed

    private void higieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higieneActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Higiene"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_higieneActionPerformed

    private void cosméticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosméticosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Cosméticos"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_cosméticosActionPerformed

    private void selosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Selos"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_selosActionPerformed

    private void moedas_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moedas_notasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Moedas e Notas"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_moedas_notasActionPerformed

    private void medalhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medalhasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Medalhas"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_medalhasActionPerformed

    private void antiguidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiguidadesActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Antiguidades"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_antiguidadesActionPerformed

    private void arteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arteActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Arte"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_arteActionPerformed

    private void vestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vestuarioActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Vestuário"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_vestuarioActionPerformed

    private void acessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessoriosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Acessórios"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_acessoriosActionPerformed

    private void brinquedosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brinquedosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Brinquedos"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_brinquedosActionPerformed

    private void fitnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnessActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Fitness e Musculação"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_fitnessActionPerformed

    private void filmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmesActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Filmes e Cinema"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_filmesActionPerformed

    private void musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Música"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_musicaActionPerformed

    private void caca_pescaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caca_pescaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Caça e Pesca"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_caca_pescaActionPerformed

    private void campismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campismoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Campismo"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_campismoActionPerformed

    private void natacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natacaoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Natação"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_natacaoActionPerformed

    private void audiotvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audiotvActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Áudio Tv e Vídeo"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_audiotvActionPerformed

    private void consolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Consolas"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_consolasActionPerformed

    private void fotografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotografiaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Fotografia"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_fotografiaActionPerformed

    private void informaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informaticaActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Informática"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_informaticaActionPerformed

    private void telemoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telemoveisActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Telemóveis e Telefones"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_telemoveisActionPerformed

    private void gadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gadActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Gadgets"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_gadActionPerformed

    private void circuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuitosActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String[] campos = {"c"};
        Object[] valores = {"Circuitos"};

        Set<Anuncio> anuncios = root.getSistema().procurarAnuncAvanc(root.getSistema().getAnuncios().values(), campos, valores, 1);
        
        root.setBody(new Pesquisa_Resultado(root, anuncios), "Pesquisa");
    }//GEN-LAST:event_circuitosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink acessorios;
    private org.jdesktop.swingx.JXHyperlink animais;
    private org.jdesktop.swingx.JXHyperlink antiguidades;
    private org.jdesktop.swingx.JXHyperlink arte;
    private org.jdesktop.swingx.JXHyperlink audiotv;
    private org.jdesktop.swingx.JXHyperlink auto;
    private org.jdesktop.swingx.JXHyperlink banda_desenhada;
    private org.jdesktop.swingx.JXHyperlink brinquedos;
    private org.jdesktop.swingx.JXHyperlink caca_pesca;
    private org.jdesktop.swingx.JXHyperlink campismo;
    private org.jdesktop.swingx.JXHyperlink casa_jardim;
    private org.jdesktop.swingx.JXHyperlink circuitos;
    private org.jdesktop.swingx.JXHyperlink colec_arte;
    private org.jdesktop.swingx.JXHyperlink consolas;
    private org.jdesktop.swingx.JXHyperlink cosméticos;
    private org.jdesktop.swingx.JXHyperlink desporto_entret;
    private org.jdesktop.swingx.JXHyperlink filmes;
    private org.jdesktop.swingx.JXHyperlink fitness;
    private org.jdesktop.swingx.JXHyperlink fotografia;
    private org.jdesktop.swingx.JXHyperlink futebol;
    private org.jdesktop.swingx.JXHyperlink gad;
    private org.jdesktop.swingx.JXHyperlink higiene;
    private org.jdesktop.swingx.JXHyperlink imovies;
    private org.jdesktop.swingx.JXHyperlink informatica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink32;
    private org.jdesktop.swingx.JXHyperlink jardinagem;
    private org.jdesktop.swingx.JXHyperlink literatura;
    private org.jdesktop.swingx.JXHyperlink literatura_infantil;
    private org.jdesktop.swingx.JXHyperlink livros_revistas;
    private org.jdesktop.swingx.JXHyperlink manuais_escolares;
    private org.jdesktop.swingx.JXHyperlink medalhas;
    private org.jdesktop.swingx.JXHyperlink mobilia;
    private org.jdesktop.swingx.JXHyperlink moda;
    private org.jdesktop.swingx.JXHyperlink moedas_notas;
    private org.jdesktop.swingx.JXHyperlink musica;
    private org.jdesktop.swingx.JXHyperlink natacao;
    private org.jdesktop.swingx.JXHyperlink outros;
    private org.jdesktop.swingx.JXHyperlink pecas_auto;
    private org.jdesktop.swingx.JXHyperlink plantas_flores;
    private org.jdesktop.swingx.JXHyperlink revistas;
    private org.jdesktop.swingx.JXHyperlink saude;
    private org.jdesktop.swingx.JXHyperlink selos;
    private org.jdesktop.swingx.JXHyperlink tec_eletro;
    private org.jdesktop.swingx.JXHyperlink telemoveis;
    private org.jdesktop.swingx.JXHyperlink veiculos;
    private org.jdesktop.swingx.JXHyperlink vestuario;
    // End of variables declaration//GEN-END:variables
}
