/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation_Layer.Header;

import Presentation_Layer.Registo.Registo_Main;
import Presentation_Layer.Sale_Squared;
import javax.swing.JDialog;

/**
 *
 * @author ricardobranco
 */
public class Visitante_Panel extends javax.swing.JPanel {

    private final Sale_Squared root;

    /**
     * Creates new form Visitante_Panel
     */
    public Visitante_Panel(final Sale_Squared root) {
        initComponents();
        this.root = root;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registo = new javax.swing.JButton();
        entrar = new javax.swing.JButton();

        registo.setText("Registar");
        registo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registoActionPerformed(evt);
            }
        });

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(entrar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(registo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(registo)
                .add(entrar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registoActionPerformed
        // TODO add your handling code here:
        root.setBody(new Registo_Main(root), "Registo");
    }//GEN-LAST:event_registoActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        JDialog frame = new Entrar(root);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_entrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JButton registo;
    // End of variables declaration//GEN-END:variables
}
